# Generated by Django 3.2.4 on 2021-06-04 19:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buffet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.DateField(default=datetime.datetime(2021, 6, 4, 19, 17, 4, 208395, tzinfo=utc))),
                ('btime', models.TimeField(default=datetime.datetime(2021, 6, 4, 19, 17, 4, 208395, tzinfo=utc))),
                ('partysize', models.IntegerField(max_length=3)),
                ('bfirst_name', models.CharField(max_length=100)),
                ('blast_name', models.CharField(max_length=100)),
                ('bemail', models.EmailField(max_length=300)),
                ('bphone', models.IntegerField(max_length=10)),
                ('blocation', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField(max_length=3)),
                ('itemname', models.CharField(max_length=50)),
                ('keep', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('itemof', models.CharField(max_length=20)),
                ('keep', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=300)),
                ('phone', models.IntegerField(max_length=10)),
                ('noofguests', models.IntegerField(max_length=3)),
                ('rdate', models.DateField(default=datetime.datetime(2021, 6, 4, 19, 17, 4, 207395, tzinfo=utc))),
                ('rtime', models.TimeField(default=datetime.datetime(2021, 6, 4, 19, 17, 4, 207395, tzinfo=utc))),
                ('reservationtype', models.CharField(max_length=200)),
                ('mention', models.TextField()),
            ],
        ),
    ]
